### PR TITLE
Curated 1 mapping (sumir)

### PR DESCRIPTION
**Pull request by sumirp**
Curated 1 predicted mapping to incorrect mapping

### CODE REVIEW

**Review by cthoyt — APPROVED** [review]
@sumirp this looks like a good curation! Note I made an update to include your ORCID identifier to properly give credit, so if you continue working on this branch you should pull from GitHub first. Are you planning on sending additional curations?

**Comment by sumirp** [comment]
@cthoyt Thank you for your feedback. This is my first attempt for the mappings, so I would request you can merge this branch and from the next curation onwards I will try and add multiple commits in 1 branch.
Thank you

**Comment by cthoyt** [comment]
@sumirp now that you've got a merge, you will need to reconcile your master branch with the Biopragmatics master branch before continuing forward. See https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork

**Comment by sumirp** [comment]
@cthoyt. Thank you, I will sync the fork.

**Pull request merged**
