### PR TITLE
Add AGRO-AGROVOC mappings

### PR DESCRIPTION
**Pull request by cthoyt**
This PR adds predicted mappings between AGRO labels/synonyms and the English preferred terms from AGROVOC. The SPARQL query could be extended to use other alternative labels if desired.

@KrishnaTO can you do a sanity check - I'm surprised the number of suggestions is quite low

### CODE REVIEW

**Comment by KrishnaTO** [comment]
A quick check shows good matches, wherever labels match or def exists. 

This is a great tool! Do you know if the AGROVOC synonyms are currently checked? Not to mention, our ontology also has lots of common labels as synonyms instead of the rdfs:labels.

**Comment by cthoyt** [comment]
> 

maybe it wasn't clear from the description but all of the labels/synonyms from AGRO are considered. Currently only the preferred labels from AGROVOC are considered. That could be updated if you think it's important.

**Comment by KrishnaTO** [comment]
Got it, compared to the [previous mappings](https://github.com/AgriculturalSemantics/agro/blob/master/src/referenceMaterial/agro_agrovoc_mapping.tsv), some terms have changed between either one of the sources. 

As well, AGROVOC seems to use "ENTRY TERMS" for synonyms ([example](https://agrovoc.fao.org/browse/agrovoc/en/page/c_6138)), so there may be some mods there. 

But so happy with this tool, thanks @cthoyt !

**Comment by KrishnaTO** [comment]
@cthoyt How did you bypass the agro parsing error? 
I was attempting to run the "scripts/generate_agrovoc_mappings.py" file locally, and can't figure out how you parsed AGRO?

```
File "/.../.local/lib/python3.8/site-packages/pronto/parsers/rdfxml.py", line 182, in _compact_datatype
    raise ValueError(f"invalid datatype: {iri!r}")
ValueError: invalid datatype: 'http://www.w3.org/2000/01/rdf-schema#anyURI'
```

Note: I do have the dev versions of pyobo, pystow, and biomappings you updated. Did you mod pronto as well?

**Comment by cthoyt** [comment]
@KrishnaTO I just went through PyStow and PyOBO to make sure there's a a PyPI release that's sufficient to make this work, so you can just get the new releases from `pip uninstall pystow pyobo bioregistry && pip install --upgrade pystow bioregistry pyobo`. Let me know if that fixes it - otherwise the error you showed is because it's using an RDF/XML reader for AGRO, which might be because it's not finding the recently added OBO link

**Comment by KrishnaTO** [comment]
It found the right path for AgrO after the mentioned reinstallations.

**Comment by KrishnaTO** [comment]
@cthoyt Regarding the sanity check, AgrO has 1190 terms within its namespace (AGRO_), so 162 matches using label and synonyms (not sure if searches definitions?) isn't bad. 
A lot terms may not have the correct synonyms in either database, so there are has to be additional manual curation work to add those.

The mentioned predictions were curated [here](https://github.com/krishnaTO/biomappings/tree/curate-agro-agrovoc-mappings) with 142/162 positive exact matches. Let me know if want to merge and create a PR to this this branch.

**Comment by cthoyt** [comment]
@KrishnaTO I'm sorry I missed your comment - it's great you triaged these! I will definitely merge them in a separate PR :)

**Pull request merged**
